force-app/main/default/objects/Fiscal_Year__c/Fiscal_Year__c.object-meta.xml
<CustomObject>
    <description>Fiscal Year</description>
    <label>Fiscal Year</label>
    <nameField>
        <label>Fiscal Year</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fiscal Year</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fiscal_Year__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <description>Year in Number Format</description>
    <formula>value(Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/pfc_Annual_Contributions__c/pfc_Annual_Contributions__c.object-meta.xml
<CustomObject>
    <description>Custom Object that Tracks Annual Contribution</description>
    <label>Annual Contribution</label>
    <nameField>
        <displayFormat>CON-{00000000}</displayFormat>
        <label>Annual Contributions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Annual Contributions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/pfc_Annual_Contributions__c/fields/Affects_RRSP_Limit__c.field-meta.xml
<CustomField>
    <fullName>Affects_RRSP_Limit__c</fullName>
    <description>Identifies if this Contribution counts towards RRSP Limit</description>
    <formula>ISPICKVAL(Contribution_Type__c , 'RRSP') || ISPICKVAL( Contribution_Type__c , 'DPSP') || ISPICKVAL( Contribution_Type__c , 'Pension')</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Identifies if this Contribution counts towards RRSP Limit</inlineHelpText>
    <label>Affects RRSP Limit?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pfc_Annual_Contributions__c/fields/Affects_TFSA_Limit__c.field-meta.xml
<CustomField>
    <fullName>Affects_TFSA_Limit__c</fullName>
    <description>Identifies if this Contribution counts towards TFSA Limit</description>
    <formula>ISPICKVAL(Contribution_Type__c , 'TFSA')</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Identifies if this Contribution counts towards TFSA Limit</inlineHelpText>
    <label>Affects TFSA Limit?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pfc_Annual_Contributions__c/fields/Contribution_Amount__c.field-meta.xml
<CustomField>
    <fullName>Contribution_Amount__c</fullName>
    <description>Annual Contribution Amount</description>
    <inlineHelpText>Annual Contribution Amount</inlineHelpText>
    <label>Contribution Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/pfc_Annual_Contributions__c/fields/Contribution_Applies_to_FY__c.field-meta.xml
<CustomField>
    <fullName>Contribution_Applies_to_FY__c</fullName>
    <description>Contribution Applies to Fiscal Year</description>
    <formula>IF (ISPICKVAL( Contribution_Type__c ,'RRSP'),  Fiscal_Year__r.Year__c +1 ,  Fiscal_Year__r.Year__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Contribution Applies to Fiscal Year</inlineHelpText>
    <label>Contribution Applies to FY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/pfc_Annual_Contributions__c/fields/Contribution_Description__c.field-meta.xml
<CustomField>
    <fullName>Contribution_Description__c</fullName>
    <description>Contribution Description</description>
    <inlineHelpText>Contribution Description</inlineHelpText>
    <label>Contribution Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/pfc_Annual_Contributions__c/fields/Contribution_Source__c.field-meta.xml
<CustomField>
    <fullName>Contribution_Source__c</fullName>
    <label>Contribution Source</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Self</fullName>
            </value>
            <value>
                <fullName>Company</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/pfc_Annual_Contributions__c/fields/Contribution_Type__c.field-meta.xml
<CustomField>
    <fullName>Contribution_Type__c</fullName>
    <description>Type of Contribution</description>
    <inlineHelpText>Type of Contribution</inlineHelpText>
    <label>Contribution Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RRSP</fullName>
            </value>
            <value>
                <fullName>TFSA</fullName>
            </value>
            <value>
                <fullName>DPSP</fullName>
            </value>
            <value>
                <fullName>HBP Re-Payment</fullName>
            </value>
            <value>
                <fullName>Pension</fullName>
            </value>
            <value>
                <fullName>RESP</fullName>
            </value>
            <value>
                <fullName>Saving Long Term</fullName>
            </value>
            <value>
                <fullName>Saving Short Term</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/pfc_Annual_Contributions__c/fields/Fiscal_Year__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Year__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Fiscal Year</description>
    <label>Fiscal Year</label>
    <referenceTo>pfc_Fiscal_Year__c</referenceTo>
    <relationshipLabel>Annual Contributions</relationshipLabel>
    <relationshipName>Annual_Contributions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pfc_Annual_Contributions__c/fields/Individual__c.field-meta.xml
<CustomField>
    <fullName>Individual__c</fullName>
    <description>Individual</description>
    <label>Individual</label>
    <referenceTo>pfc_Individual__c</referenceTo>
    <relationshipLabel>Annual Contributions</relationshipLabel>
    <relationshipName>Annual_Contributions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/pfc_Annual_Contributions__c/fields/Individual_Name__c.field-meta.xml
<CustomField>
    <fullName>Individual_Name__c</fullName>
    <description>Individual Name</description>
    <formula>Individual__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Individual Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/pfc_Annual_Contributions__c/fields/Pre_Tax_Contribution__c.field-meta.xml
<CustomField>
    <fullName>Pre_Tax_Contribution__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if this contribution was deducted Pre/post tax</description>
    <inlineHelpText>Indicates if this contribution was deducted Pre/post tax</inlineHelpText>
    <label>Pre Tax Contribution</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pfc_Annual_Limit__c/pfc_Annual_Limit__c.object-meta.xml
<CustomObject>
    <description>Stores a Person's Annual Limits</description>
    <label>Annual Limit</label>
    <nameField>
        <displayFormat>LIM-{00000000}</displayFormat>
        <label>Annual Limitis Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Annual Limits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/pfc_Annual_Limit__c/fields/Fiscal_Year__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Year__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Fiscal year</description>
    <label>Fiscal Year</label>
    <referenceTo>pfc_Fiscal_Year__c</referenceTo>
    <relationshipLabel>Annual Limits</relationshipLabel>
    <relationshipName>Annual_Limits</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pfc_Annual_Limit__c/fields/Individual__c.field-meta.xml
<CustomField>
    <fullName>Individual__c</fullName>
    <description>Individual</description>
    <label>Individual</label>
    <referenceTo>pfc_Individual__c</referenceTo>
    <relationshipLabel>Annual Limits</relationshipLabel>
    <relationshipName>Annual_Limits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/pfc_Annual_Limit__c/fields/RRSP_Limit__c.field-meta.xml
<CustomField>
    <fullName>RRSP_Limit__c</fullName>
    <defaultValue>0</defaultValue>
    <description>RRSP Limit for the Person in the FY</description>
    <inlineHelpText>RRSP Limit for the Person in the FY</inlineHelpText>
    <label>RRSP Limit</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/pfc_Annual_Limit__c/fields/RRSP_Limit_Used__c.field-meta.xml
<CustomField>
    <fullName>RRSP_Limit_Used__c</fullName>
    <defaultValue>0</defaultValue>
    <description>RRSP Limit Used in the Calendar year</description>
    <inlineHelpText>RRSP Limit Used in the Calendar year</inlineHelpText>
    <label>RRSP Limit Used</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/pfc_Annual_Limit__c/fields/TFSA_Limit__c.field-meta.xml
<CustomField>
    <fullName>TFSA_Limit__c</fullName>
    <defaultValue>0</defaultValue>
    <description>TFSA Limit for the Person for the year</description>
    <inlineHelpText>TFSA Limit for the Person for the year</inlineHelpText>
    <label>TFSA Limit</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/pfc_Annual_Limit__c/fields/TFSA_Limit_Used__c.field-meta.xml
<CustomField>
    <fullName>TFSA_Limit_Used__c</fullName>
    <defaultValue>0</defaultValue>
    <description>TFSA Limit Used int eh Calendar Year</description>
    <label>TFSA Limit Used</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/pfc_Fiscal_Year__c/pfc_Fiscal_Year__c.object-meta.xml
<CustomObject>
    <description>Fiscal Year</description>
    <label>Fiscal Year</label>
    <nameField>
        <label>Fiscal Year</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fiscal Year</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pfc_Individual__c/pfc_Individual__c.object-meta.xml
<CustomObject>
    <description>Information about a Person</description>
    <label>Individual</label>
    <nameField>
        <label>Person Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Individuals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pfc_Individual__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <description>Family Name</description>
    <label>Family</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/pfc_Individual__c/fields/Order_in_Family__c.field-meta.xml
<CustomField>
    <fullName>Order_in_Family__c</fullName>
    <description>Order of the Person in Family</description>
    <label>Order in Family</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/classes/Contribution.cls
/**
 * Created by skvarma on 2017-11-29.
 */

public with sharing class Contribution {

    @AuraEnabled
    public static List<pfc_Annual_Contributions__c> getAnnualContributions(String familyName, Integer fiscalYear){
        return [
                SELECT
                        Affects_RRSP_Limit__c,
                        Affects_TFSA_Limit__c,
                        Contribution_Amount__c,
                        Contribution_Applies_to_FY__c,
                        Contribution_Description__c,
                        Contribution_Source__c,
                        Contribution_Type__c,
                        Fiscal_Year__c,
                        Id,
                        Individual__c,
                        Individual_Name__c,
                        Name,
                        Pre_Tax_Contribution__c
                FROM pfc_Annual_Contributions__c
                WHERE Individual__r.Family__c = :familyName AND Fiscal_Year__r.Year__c = :fiscalYear
                ORDER BY Individual__c,Contribution_Type__c, Contribution_Source__c];

    }

    @AuraEnabled
    public static List<pfc_Annual_Limit__c> getAnnualLimits(String familyName, Integer fiscalYear){
        return [
                SELECT
                        Fiscal_Year__c,
                        Id,
                        Individual__c,
                        Name,
                        RRSP_Limit__c,
                        RRSP_Limit_Used__c,
                        TFSA_Limit__c,
                        TFSA_Limit_Used__c
                FROM pfc_Annual_Limit__c
                WHERE Individual__r.Family__c = :familyName AND Fiscal_Year__r.Year__c = :fiscalYear
        ];
    }

    @AuraEnabled
    public static List<pfc_Individual__c> getFamilyMembers(String familyName){
        return [
                SELECT
                        DOB__c,
                        Family__c,
                        Id,
                        Name,
                        Order_in_Family__c
                FROM pfc_Individual__c
                WHERE Family__c = :familyName
                ORDER BY Order_in_Family__c asc];
    }

}