force-app/main/default/objects/Fiscal_Year__c/Fiscal_Year__c.object-meta.xml
<CustomObject>
    <description>Fiscal Year</description>
    <label>Fiscal Year</label>
    <nameField>
        <label>Fiscal Year</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fiscal Year</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fiscal_Year__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <description>Year in Number Format</description>
    <formula>value(Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/pfc_Fiscal_Year__c/pfc_Fiscal_Year__c.object-meta.xml
<CustomObject>
    <description>Fiscal Year</description>
    <label>Fiscal Year</label>
    <nameField>
        <label>Fiscal Year</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fiscal Year</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pfc_Income__c/pfc_Income__c.object-meta.xml
<CustomObject>
    <description>Custom Object to Track Income for a person per Financial year.</description>
    <label>Income</label>
    <nameField>
        <displayFormat>IN-{00000000}</displayFormat>
        <label>Income Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Income</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/pfc_Income__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Income Amount</description>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/pfc_Income__c/fields/Fiscal_Year__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Year__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Fiscal year for Income</description>
    <label>Fiscal Year</label>
    <referenceTo>pfc_Fiscal_Year__c</referenceTo>
    <relationshipLabel>Income</relationshipLabel>
    <relationshipName>Income</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pfc_Income__c/fields/Income_Source__c.field-meta.xml
<CustomField>
    <fullName>Income_Source__c</fullName>
    <description>Source of the Income</description>
    <label>Income Source</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salary</fullName>
            </value>
            <value>
                <fullName>Bonus</fullName>
            </value>
            <value>
                <fullName>Investment Income</fullName>
            </value>
            <value>
                <fullName>Rental Income</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/pfc_Income__c/fields/Income_Tax_Type__c.field-meta.xml
<CustomField>
    <fullName>Income_Tax_Type__c</fullName>
    <description>Type of income tax that applies on the incoming Income</description>
    <label>Income Tax Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Personal Income Tax Rate</fullName>
            </value>
            <value>
                <fullName>Capital Gain Income Tax Rate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/pfc_Income__c/fields/Individual__c.field-meta.xml
<CustomField>
    <fullName>Individual__c</fullName>
    <description>Individual</description>
    <label>Individual</label>
    <referenceTo>pfc_Individual__c</referenceTo>
    <relationshipLabel>Income</relationshipLabel>
    <relationshipName>Income</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/pfc_Income__c/fields/Individual_Name__c.field-meta.xml
<CustomField>
    <fullName>Individual_Name__c</fullName>
    <description>Individual's name form the Parent</description>
    <formula>Individual__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Individual Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/pfc_Individual__c/pfc_Individual__c.object-meta.xml
<CustomObject>
    <description>Information about a Person</description>
    <label>Individual</label>
    <nameField>
        <label>Person Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Individuals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pfc_Individual__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <description>Family Name</description>
    <label>Family</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/classes/Income.cls
/**
 * Created by skvarma on 2017-11-29.
 */

public with sharing class Income {


    @AuraEnabled
    public Static List<pfc_Income__c> getFamilyFYIncome(String familyName, Integer fiscalYear){
        return [
                SELECT
                        Amount__c,
                        Fiscal_Year__c,
                        Fiscal_Year__r.Name,
                        Id,
                        Income_Source__c,
                        Income_Tax_Type__c,
                        Individual__c,
                        Individual_Name__c,
                        Name
                FROM pfc_Income__c WHERE Individual__r.Family__c = :familyName AND Fiscal_Year__r.Year__c = :fiscalYear
                ORDER BY Individual__c, Amount__c DESC];
    }

    @AuraEnabled
    public Static Decimal getSummaryFYIncome(List<pfc_Income__c> incomeLst){
        Decimal totalIncome = 0.0;
        for(pfc_Income__c income:incomeLst){
            totalIncome = totalIncome + income.Amount__c;
        }
        return totalIncome;
    }

}