force-app/main/default/objects/pfc_Individual__c/pfc_Individual__c.object-meta.xml
<CustomObject>
    <description>Information about a Person</description>
    <label>Individual</label>
    <nameField>
        <label>Person Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Individuals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pfc_Individual__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <description>Family Name</description>
    <label>Family</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/pfc_Individual__c/fields/Order_in_Family__c.field-meta.xml
<CustomField>
    <fullName>Order_in_Family__c</fullName>
    <description>Order of the Person in Family</description>
    <label>Order in Family</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/classes/Family.cls
/**
 * Created by skvarma on 2017-11-27.
 */

public with sharing class Family {

    @AuraEnabled
    public Static List<pfc_Individual__c> getFamilyMembers(String familyName){
        return [
                SELECT
                        DOB__c,
                        Family__c,
                        Id,
                        Name,
                        Order_in_Family__c
                FROM pfc_Individual__c
                WHERE Family__c = :familyName
                ORDER BY Order_in_Family__c asc];
    }

}